[board]
# available board themes: green, red, blue, orange, black, dark, purple, teal, gray, chesscom, lichess
# you can write which one do you want or you want to try
theme =
# default is "teal" if you don't want to change just leave it empty
# btw don't need to restart the app just press 'F5' in game to reload config
