name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat

    - name: Install SFML via vcpkg
      run: |
        ./vcpkg/vcpkg install sfml:x64-windows

    - name: Configure CMake
      run: |
        cmake -B build -S . `
          "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET=x64-windows
          
    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Chess-Game-Windows
        path: build/Release/
